[PHP]
extension_dir="ext"
date.timezone="Asia/Karachi"
memory_limit=512M
max_execution_time=120
post_max_size=16M
upload_max_filesize=8M
variables_order="GPCS"

extension=curl
extension=fileinfo
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=sodium
extension=zip
