@extends('layouts.storefront')
@section('title', 'Secure checkout')
@section('body-class', 'checkout-body')

@section('content')
<div class="checkout-progress"><div class="container"><span class="done">1 <b>Cart</b></span><i></i><span class="active">2 <b>Checkout</b></span><i></i><span>3 <b>Confirmation</b></span></div></div>
<section class="container checkout-layout">
    <form id="checkout-form" class="checkout-form" action="{{ route('checkout.store') }}" method="post">@csrf
        <input type="hidden" name="checkout_token" value="{{ $checkoutToken }}">
        <div class="checkout-card"><div class="checkout-card__title"><span>1</span><div><h1>Contact information</h1><p>We’ll send your receipt and delivery updates here.</p></div></div><div class="form-grid"><label class="field field--full">Full name<input name="customer_name" value="{{ old('customer_name', $customer?->name) }}" required autocomplete="name"></label><label class="field">Email address<input type="email" name="customer_email" value="{{ old('customer_email', $customer?->email) }}" required autocomplete="email"></label><label class="field">Phone number<input name="customer_phone" value="{{ old('customer_phone', $customer?->phone) }}" required autocomplete="tel" placeholder="+971 50 000 0000"></label></div></div>
        <div class="checkout-card"><div class="checkout-card__title"><span>2</span><div><h2>Delivery address</h2><p>Enter a complete UAE delivery address.</p></div></div><div class="form-grid"><label class="field field--full">Address line 1<input name="address_line_1" value="{{ old('address_line_1') }}" required autocomplete="address-line1" placeholder="Building, street, area"></label><label class="field field--full">Address line 2 <small>Optional</small><input name="address_line_2" value="{{ old('address_line_2') }}" autocomplete="address-line2" placeholder="Apartment, suite, warehouse"></label><label class="field">City<input name="city" value="{{ old('city') }}" required autocomplete="address-level2"></label><label class="field">Emirate<select name="emirate" required><option value="">Choose emirate</option>@foreach(['Abu Dhabi','Ajman','Dubai','Fujairah','Ras Al Khaimah','Sharjah','Umm Al Quwain'] as $emirate)<option value="{{ $emirate }}" @selected(old('emirate')===$emirate)>{{ $emirate }}</option>@endforeach</select></label><label class="field">Postal code <small>Optional</small><input name="postal_code" value="{{ old('postal_code') }}" autocomplete="postal-code"></label><label class="field field--full">Delivery notes <small>Optional</small><textarea name="notes" rows="3" placeholder="Access instructions or preferred contact details">{{ old('notes') }}</textarea></label></div></div>
        <div class="checkout-card"><div class="checkout-card__title"><span>3</span><div><h2>Payment method</h2><p>Payment data is handled by the selected secure provider.</p></div></div><div class="payment-options"><label><input type="radio" name="payment_method" value="cod" @checked(old('payment_method','cod')==='cod')><span><b>Cash on delivery</b><small>Pay when your order arrives</small></span><em>AED</em></label><label><input type="radio" name="payment_method" value="stripe" @checked(old('payment_method')==='stripe')><span><b>Card with Stripe</b><small>Visa, Mastercard and supported wallets</small></span><em>VISA</em></label><label><input type="radio" name="payment_method" value="paypal" @checked(old('payment_method')==='paypal')><span><b>PayPal</b><small>Use your PayPal balance or linked card</small></span><em>PayPal</em></label></div>@if(config('services.payments.demo'))<div class="demo-notice"><strong>Demo payment mode is on.</strong> Stripe and PayPal options will create a pending demo order and will not charge you.</div>@endif</div>
        <label class="terms-check"><input type="checkbox" name="terms" value="1" required> I agree to the terms, privacy policy and delivery conditions.</label><button class="button button--full button--buy checkout-submit" type="submit">Place order · AED {{ number_format($summary['total'],2) }}</button>
    </form>
    <aside class="checkout-summary"><h2>Your order <span>{{ $summary['count'] }} items</span></h2><div class="checkout-summary__items">@foreach($summary['items'] as $line)<div><span class="checkout-summary__image"><img src="{{ $line['product']->imageUrl() }}" alt=""><b>{{ $line['quantity'] }}</b></span><p><strong>{{ $line['product']->name }}</strong>@if($line['variant'])<small>{{ $line['variant'] }}</small>@endif</p><em>AED {{ number_format($line['line_total'],2) }}</em></div>@endforeach</div><div class="checkout-summary__totals"><p><span>Subtotal</span><strong>AED {{ number_format($summary['subtotal'],2) }}</strong></p>@if($summary['discount']>0)<p class="discount-line"><span>Discount</span><strong>− AED {{ number_format($summary['discount'],2) }}</strong></p>@endif<p><span>Delivery</span><strong>{{ $summary['shipping'] ? 'AED '.number_format($summary['shipping'],2) : 'FREE' }}</strong></p><p class="total"><span>Total</span><strong>AED {{ number_format($summary['total'],2) }}</strong></p></div><div class="checkout-support">Need help? <a href="tel:+971523993759">+971 52 399 3759</a></div></aside>
</section>
@endsection
