@extends('layouts.storefront')
@section('title', 'About us')
@section('description', 'Discover how SNH Packing grew into a trusted UAE supplier for packaging, hygiene and everyday essentials.')
@section('content')
<div class="page-hero about-hero"><div class="container"><nav class="breadcrumbs"><a href="{{ route('home') }}">Home</a><span>›</span><span>About us</span></nav><span class="eyebrow">Built on service</span><h1>Empowering hygiene.<br><em>Sustainably.</em></h1><p>We make it easier for UAE businesses and households to choose dependable, better-considered everyday products.</p></div></div>
<section class="container about-story"><div><span class="eyebrow">Our story</span><h2>From 25 tons to more than 400 tons every month.</h2><p>SNH began with a straightforward promise: keep the products customers rely on available, fairly priced and supported by people who understand their work. What started at 25 tons has grown into a diverse operation handling more than 400 tons per month.</p><p>Today our 2,500+ product range spans food packaging, hygiene, tissue, grocery and pet care, serving independent businesses, hospitality groups and households throughout the UAE.</p><div class="stats-grid"><div><strong>2,500+</strong><span>products</span></div><div><strong>400t+</strong><span>monthly volume</span></div><div><strong>7</strong><span>emirates served</span></div></div></div><div class="about-story__visual"><div><span>Reliable stock</span><strong>Made practical.</strong></div><div><span>Responsive people</span><strong>Made personal.</strong></div><div><span>Better materials</span><strong>Made possible.</strong></div></div></section>
<section class="values-section"><div class="container"><div class="section-heading section-heading--center"><div><span class="eyebrow">Where we’re going</span><h2>Practical progress, together.</h2></div></div><div class="values-grid"><article><span>01</span><h3>Our mission</h3><p>To become the UAE’s first choice for hygiene and packaging by pairing dependable service with a growing range of eco-conscious products and custom solutions.</p></article><article><span>02</span><h3>Our vision</h3><p>To lead the region’s disposable-products industry toward a more sustainable future without compromising usability, availability or value.</p></article><article><span>03</span><h3>Our promise</h3><p>Clear advice, honest lead times and products selected for real-world hospitality, retail, office and home use.</p></article></div></div></section>
<section class="container sustainability-section"><div class="sustainability-card"><span class="eyebrow">Smarter material choices</span><h2>Small changes scale into meaningful ones.</h2><p>Our expanding eco-friendly range includes bagasse, paper and wooden solutions designed to help customers replace conventional single-use formats where practical.</p><a class="button button--lime" href="{{ route('categories.show','eco-friendly') }}">Explore eco-friendly</a></div><div class="sustainability-points"><div><span>♧</span><p><strong>Lower-impact alternatives</strong><small>Compostable and responsibly sourced formats</small></p></div><div><span>◎</span><p><strong>Right-size guidance</strong><small>Reduce waste by choosing the right format first</small></p></div><div><span>↻</span><p><strong>Continuous improvement</strong><small>A range that evolves with customer needs</small></p></div></div></section>
<section class="about-cta"><div class="container"><div><span class="eyebrow">Let’s build what’s next</span><h2>Need a dependable supply partner?</h2><p>Talk to our team about wholesale quantities, recurring supply or custom packaging.</p></div><a class="button button--lime" href="{{ route('contact') }}">Start a conversation</a></div></section>
@endsection
